### PR TITLE
Fixes the version check.

### LINKED ISSUE #18: The NodeJS version checker in the CLI is wrong
The current check transforms NodeJS v18.3 to the number `18.3` and transforms v18.11 to `18.11`.
This means that `18.3 > 18.11` which is not correct according to semver.
You have to make the minor a two digit number by zero padding it if it's only one digit.
So v18.3 would become the number `18.03`...

### PR DESCRIPTION
**Pull request by evert**
Fixes #18.

### CODE REVIEW

**Comment by evert** [comment]
Noticed it's been a while this was looked at @coreyarms . If you want me to just merge these (and my other PRs) and release, let me know! i'll need access to the npm project

**Comment by evert** [comment]
no pressure!

**Comment by coreyarms** [comment]
Hey really sorry I must have missed the notification for this. I invited you to the npm project.

I'll publish the new version to npm with this and the 2 other merged PRs. It's currently v1.0.7, do you think it should be v1.0.8 or v1.1.0 (since technically there's a new feature of supporting MariaDB) ?

**Comment by evert** [comment]
Up to you about the versions! Could also be considered a bug =) but if you feel it's worth 1.1.0 go for it:P My NPM account is `evrt`

**Comment by coreyarms** [comment]
published 1.0.8 and sent you the npm invitation. thanks!

**Comment by evert** [comment]
Awesome! I dont think I'll publish without checking with you first, but in case you're MIA I might ;)

**Pull request merged**
